export const HERO_SLIDES = [
  {
    id: "apartments-fast",
    eyebrow: "Featured Campaign",
    title: "Sell Apartments Faster with",
    highlight: "Precision Ads",
    description:
      "10-Day Facebook & Instagram campaigns built for Ethiopian real estate — more WhatsApp leads, more viewings, more closings.",
    ctaLabel: "Explore Packages",
    ctaHref: "/packages",
    secondaryLabel: "How It Works",
    secondaryHref: "/about",
    image:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Modern apartment building exterior at dusk",
    accent: "from-navy via-[#152a4a] to-[#0d1b33]",
    badge: "Apartments",
    metricLabel: "Avg. Lead Lift",
    metricValue: "+214%",
    metricHint: "in 10-Day campaigns",
  },
  {
    id: "homes-viewings",
    eyebrow: "Property Spotlight",
    title: "Fill Your Calendar with",
    highlight: "Home Viewings",
    description:
      "Targeted ads that put villas and family homes in front of serious buyers — so your team spends time on real visits, not cold inquiries.",
    ctaLabel: "Start Booking",
    ctaHref: "/packages",
    secondaryLabel: "View Packages",
    secondaryHref: "/packages",
    image:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Contemporary villa with landscaped front yard",
    accent: "from-[#1a1410] via-[#2a1f14] to-navy",
    badge: "Villas & Homes",
    metricLabel: "Qualified Views",
    metricValue: "2x+",
    metricHint: "more site visits",
  },
  {
    id: "developments-leads",
    eyebrow: "Lead Engine",
    title: "WhatsApp Inquiries for",
    highlight: "New Developments",
    description:
      "Launch-ready funnels that deliver hot property leads straight to your phone — tracked, reported, and refined daily by GojoClicks.",
    ctaLabel: "Choose a Package",
    ctaHref: "/packages",
    secondaryLabel: "Talk to Us",
    secondaryHref: "/contact",
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Bright luxury living room in a new residence",
    accent: "from-[#0f1f1a] via-navy to-[#0d1b33]",
    badge: "Developments",
    metricLabel: "Leads Delivered",
    metricValue: "1,000+",
    metricHint: "on Platinum tier",
  },
];
